# Generated by Django 4.1.1 on 2022-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_description',
            field=models.TextField(default='', max_length=600, verbose_name='Детальное описание'),
        ),
    ]
